### ISSUE TITLE
Convert pokemon data to markdown for reddit?

### ISSUE THREAD

**Issue by Naturally-Delicious** [porybox/porybox#799] opened 2018-01-01 22:24 UTC

**Comment by TheSonAlsoRises** [comment] 2018-01-02 12:44
Would #34 match your request?

**Comment by Naturally-Delicious** [comment] 2018-01-05 22:03
Yes

**Comment by Raia** [comment] 2018-01-05 22:14
I'll go ahead and close this since it's a duplicate of #34.

**Closed by Raia** 2018-01-05 22:14 UTC
