### ISSUE TITLE
Add "Copy to Clipboard" Option for Basic pkm Data (Pokeball, Pokemon, Nature, IVs, OT/ID, TSV )

### ISSUE THREAD

**Issue by tacocat777** [porybox/porybox#795] opened 2017-10-05 20:01 UTC
When trading, it would be nice if the user could click a button and instantly copy a pkm's data to the user's clipboard. Wonder what data should be included/omitted. Installing a clipboard.js package may be the easiest way, but I considered maybe embedding a C# winforms app. Something like this: https://i.imgur.com/Omb08b1.jpg

**Comment by Raia** [comment] 2017-10-05 20:01
Looks like a duplicate of #34.

**Closed** 2017-10-05 20:02 UTC

**Comment by tacocat777** [comment] 2017-10-05 20:04
Sorry, I looked for copy to clipboard!

**Comment by Raia** [comment] 2017-10-05 20:04
No worries! Thanks for posting, it's nice to see some activity here :)
