### ISSUE TITLE
Returning to Main Page Before "Box Is Deleted" message

### ISSUE THREAD

**Issue by pkmnbumba** [porybox/porybox#755] opened 2017-03-11 05:04 UTC
If you press on Porygon to return to the main page after deleting a box (but before the "Box is deleted" message), the deleted box doesn't disappear until you refresh.

**Comment by YaManicKill** [comment] 2017-03-11 18:36
Duplicate of #693 :-)

**Closed by YaManicKill** 2017-03-11 18:36 UTC
