### ISSUE TITLE
Wrong total stats for EV trained pokémon

### ISSUE THREAD

**Issue by robertoxmed** [porybox/porybox#792] opened 2017-08-14 09:39 UTC
Seems there is a bug for total stats when the value is boosted/decreased by the nature.

For example this Ninetales https://www.porybox.com/#/pokemon/fb4e939b93e1ff5051f5ebba0740cae8 should have 177 Speed and 69 Attack.

**Comment by YaManicKill** [comment] 2017-08-16 08:28
Hmmm, this would probably be best on pkparse, as that's where the code for this is.

**Comment by not-an-aardvark** [comment] 2017-08-16 08:39
This might be the same issue as https://github.com/porybox/pkparse/issues/35.

**Comment by YaManicKill** [comment] 2017-08-16 09:04
Yeah, that looks like it's probably the same thing. Closing this as a duplicate of porybox/pkparse#35

**Closed by YaManicKill** 2017-08-16 09:04 UTC
Labels: bug
